using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using WindowsServiceXGlobals;

namespace p2
{
    public partial class Form1 : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            ZaladujDane();

            ZmienneGlobalne.ListaMiejscowosci = this;
            

            if (ZmienneGlobalne.ZalogowanyPraocnwik.Stan_tabelki != null)
            {

                string stanGrida = ZmienneGlobalne.ZalogowanyPraocnwik.Stan_tabelki;

                byte[] bufor = Convert.FromBase64String(stanGrida);
                MemoryStream ms = new MemoryStream(bufor);
                ms.Seek(0, SeekOrigin.Begin);

                gridView2.RestoreLayoutFromStream(ms);
                Application.DoEvents();
            }
        }

        public void Odswiez()
        {
            ZaladujDane();
        }

        private void ZaladujDane()
        {
            miejscowosciCSVTableAdapter1.Fill(miejscowosciDataSet1.miejscowosciCSV);
        }

        private void barButtonItem4_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridControl1.ShowPrintPreview();
        }

        private void Form1_FormClosed(object sender, FormClosedEventArgs e)
        {

            ZmienneGlobalne.ListaMiejscowosci = null;
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            MemoryStream ms = new MemoryStream();
            gridView2.SaveLayoutToStream(ms);
            byte[] bufor = ms.ToArray();
            string ustawieniaTabelki = Convert.ToBase64String(bufor);
            Console.WriteLine(ustawieniaTabelki);
            ZmienneGlobalne.ZalogowanyPraocnwik.Stan_tabelki = ustawieniaTabelki;
            using (MiejscowosciEntities db = new MiejscowosciEntities())
            {
                db.Pracownik.Where(f => f.PracownikId == ZmienneGlobalne.ZalogowanyPraocnwik.PracownikId).First().Stan_tabelki = ZmienneGlobalne.ZalogowanyPraocnwik.Stan_tabelki;
                db.SaveChanges();
            }



        }

        private void barButtonItem10_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            var wiersz = gridView2.GetFocusedRow() as DataRowView;
            if (wiersz != null)
            {
                if (wiersz.Row != null)
                {

                    var wybrany = wiersz.Row as MiejscowosciDataSet.miejscowosciCSVRow;
                    if (wybrany != null)
                    {
                        if (XtraMessageBox.Show(this, "Czy usunąć rekord?", "UWAGA", MessageBoxButtons.YesNo) == DialogResult.Yes)
                        {
                            using (MiejscowosciEntities db = new MiejscowosciEntities())
                            {
                                var wybrana = db.miejscowosciCSV.Where(f => f.ID == wybrany.ID).First();
                                db.miejscowosciCSV.Remove(wybrana);

                                DateTime dateTime = DateTime.Now;

                                PracownikHistoria zdarzenie = new PracownikHistoria();
                                zdarzenie.PracownikHistoriaIdP = ZmienneGlobalne.ZalogowanyPraocnwik.PracownikId;
                                zdarzenie.PracownikHistoriaCzas = dateTime;
                                zdarzenie.PracownikHistoriaOpisZdarzenia = "Usuniecie rekordu " + wybrana.kraj + " -- " + wybrana.kod_poczta + " -- " + wybrana.Miejscowosc_Poprawna + " -- " + wybrana.miejscowosc_Isotis + " -- " + wybrana.ID + " z bazy";
                                db.PracownikHistoria.Add(zdarzenie);
                                db.SaveChanges();

                                if (ZmienneGlobalne.ListaMiejscowosci != null)
                                {
                                    if (ZmienneGlobalne.ListaMiejscowosci.Visible)
                                    {
                                        ZmienneGlobalne.ListaMiejscowosci.Odswiez();
                                    }
                                }
                            }
                        }
                    }
                }
            }

        }
    }
}
