using DevExpress.XtraBars;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using WindowsServiceXGlobals;

namespace p2.Formss
{
    public partial class PS : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public PS()
        {
            InitializeComponent();
            this.FormBorderStyle = FormBorderStyle.None;
            //label1.Text = "Zalogowany jako: " + prac.PracownikLogin + ", ID:" + prac.PracownikId;
            barSubItem1.Caption = "Zalogowany jako: " + ZmienneGlobalne.ZalogowanyPraocnwik.PracownikLogin + ", ID:" + ZmienneGlobalne.ZalogowanyPraocnwik.PracownikId;

            // This line of code is generated by Data Source Configuration Wizard
            miejscowosciCSVTableAdapter1.Fill(miejscowosciDataSet1.miejscowosciCSV);
            
        }

        //Button for adding data to "Miejscowosci" database
        private void barButtonItem1_ItemClick(object sender, ItemClickEventArgs e)
        {
            //create "AddMsc Form" as a new dialog window
            AddMsc add = new AddMsc();
            add.ShowDialog();
            if (ZmienneGlobalne.ListaMiejscowosci != null)
            {
                if (ZmienneGlobalne.ListaMiejscowosci.Visible)
                {
                    ZmienneGlobalne.ListaMiejscowosci.Odswiez();
                }
            }


        }

        //opening data viewer form
        private void barButtonItem3_ItemClick(object sender, ItemClickEventArgs e)
        {

            foreach (var i in this.MdiChildren)
            {
                i.Close();
            }

            //Form1 is a ribbon form with data grid view. Here users can see and modify rows view. Every user move is saving in history table
            Form1 f1 = new Form1();
            f1.MdiParent = this;
            f1.WindowState = FormWindowState.Maximized;

            f1.Show();
        }

        //opening view with history data grid
        private void barButtonItem4_ItemClick(object sender, ItemClickEventArgs e)
        {
            Zdarzenia_historia his = new Zdarzenia_historia();
            his.MdiParent = this;
            his.WindowState = FormWindowState.Maximized;


            his.Show();
        }

        //opening view with users (workers) and informations about them
        private void Pracownicy_ItemClick(object sender, ItemClickEventArgs e)
        {

            foreach (var i in this.MdiChildren)
            {
                i.Close();
            }

            Pracownicy p = new Pracownicy();
            p.MdiParent = this;
            p.WindowState = FormWindowState.Maximized;

            p.Show();

        }


        //Logging out operation with dedicated button
        private void barButtonItem7_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (ZmienneGlobalne.GlownaForma != null)
            {
                ZmienneGlobalne.CzyWylogowanie = true;
                ZmienneGlobalne.GlownaForma.Visible = true;
                this.Close();
            }

            DateTime dateTime = DateTime.Now;
            using (MiejscowosciEntities db = new MiejscowosciEntities())
            {
                PracownikHistoria zdarzenie = new PracownikHistoria();
                zdarzenie.PracownikHistoriaIdP = ZmienneGlobalne.ZalogowanyPraocnwik.PracownikId;
                zdarzenie.PracownikHistoriaCzas = dateTime;
                zdarzenie.PracownikHistoriaOpisZdarzenia = "Wylogowanie uzytkownika";
                db.PracownikHistoria.Add(zdarzenie);
                ZmienneGlobalne.ZalogowanyPraocnwik.PracownikAktywny = false;
                db.Pracownik.Where(f => f.PracownikId == ZmienneGlobalne.ZalogowanyPraocnwik.PracownikId).First().PracownikAktywny = false;
                db.SaveChanges();

            }

            //Application.Exit();
        }

        private void PS_FormClosed(object sender, FormClosedEventArgs e)
        {
            if (ZmienneGlobalne.GlownaForma != null)
            {
                if (!ZmienneGlobalne.CzyWylogowanie)
                {
                    using (MiejscowosciEntities db = new MiejscowosciEntities())
                    {
                        db.Pracownik.Where(f => f.PracownikId == ZmienneGlobalne.ZalogowanyPraocnwik.PracownikId).First().PracownikAktywny = false;
                        db.SaveChanges();

                    }
                    ZmienneGlobalne.GlownaForma.Close();
                    
                }
            }
        }

        private void PS_FormClosing(object sender, FormClosingEventArgs e)
        {
            using (MiejscowosciEntities db = new MiejscowosciEntities())
            {
                db.Pracownik.Where(f => f.PracownikId == ZmienneGlobalne.ZalogowanyPraocnwik.PracownikId).First().PracownikAktywny = false;
                db.SaveChanges();

            }
            
        }
    }
}